// AUTO-GENERATED by scripts/sync-regions.js during `npm run build` (see the
// "prebuild" script in package.json). Do not edit by hand - any manual
// changes here are overwritten on the next build.
//
// This is fallback data only, used by src/lib/airtable.ts when Airtable is
// unreachable or misconfigured. Source of truth is the Airtable Regions
// table (base appAGZVUJmvnyDAL1), filtered to records with "Active" checked.
// Committed to git so a fresh checkout or a build without AIRTABLE_API_KEY
// set still has real fallback data instead of an empty list.
//
// Last synced: 2026-07-17T23:19:11.000Z (manually, ahead of the sync script
// existing) - 10 active regions: Surrey, Midlands, Birmingham, Hampshire,
// Cavan, Cambridgeshire, Belfast, Liverpool, Essex, London.

import type { RegionData } from "@/lib/types";

export const fallbackRegions: RegionData[] = [
  {
    slug: "surrey",
    regionName: "Surrey",
    badgeText: "Vetted Landscapers Across The UK, Ireland And Spain",
    heroHeadline: "Tell Us About Your Garden And We'll Match You With The Right Landscaper",
    heroSubheadline: "A curated network of landscapers, vetted for quality and matched to your project, your style, and your timeline. Plus an initial estimate to help you plan.",
    countyList: "For homeowners in Surrey.",
    locationPlaceholder: "e.g. GU1 1AA",
    heroImageUrl: "/images/private-family-resort.jpeg",
  },
  {
    slug: "midlands",
    regionName: "East and West Midlands",
    badgeText: "Vetted Landscapers Across The UK, Ireland And Spain",
    heroHeadline: "Tell Us About Your Garden And We'll Match You With The Right Landscaper",
    heroSubheadline: "A curated network of landscapers, vetted for quality and matched to your project, your style, and your timeline. Plus an initial estimate to help you plan.",
    countyList: "For homeowners in Leicestershire, Warwickshire, Northamptonshire and Nottinghamshire.",
    locationPlaceholder: "e.g. LE1 1AA",
    heroImageUrl: "/images/private-family-resort.jpeg",
  },
  {
    slug: "birmingham",
    regionName: "Birmingham",
    badgeText: "Vetted Landscapers Across The UK, Ireland And Spain",
    heroHeadline: "Tell Us About Your Garden And We'll Match You With The Right Landscaper",
    heroSubheadline: "A curated network of landscapers, vetted for quality and matched to your project, your style, and your timeline. Plus an initial estimate to help you plan.",
    countyList: "For homeowners in Birmingham and the West Midlands.",
    locationPlaceholder: "e.g. B1 1AA",
    heroImageUrl: "/images/private-family-resort.jpeg",
  },
  {
    slug: "hampshire",
    regionName: "Hampshire",
    badgeText: "Vetted Landscapers Across The UK, Ireland And Spain",
    heroHeadline: "Tell Us About Your Garden And We'll Match You With The Right Landscaper",
    heroSubheadline: "A curated network of landscapers, vetted for quality and matched to your project, your style, and your timeline. Plus an initial estimate to help you plan.",
    countyList: "For homeowners in Hampshire.",
    locationPlaceholder: "e.g. SO14 1AA",
    heroImageUrl: "/images/private-family-resort.jpeg",
  },
  {
    slug: "cavan",
    regionName: "Cavan",
    badgeText: "Vetted Landscapers Across The UK, Ireland And Spain",
    heroHeadline: "Tell Us About Your Garden And We'll Match You With The Right Landscaper",
    heroSubheadline: "A curated network of landscapers, vetted for quality and matched to your project, your style, and your timeline. Plus an initial estimate to help you plan.",
    countyList: "For homeowners in Cavan and surrounding counties.",
    locationPlaceholder: "e.g. H12 X285",
    heroImageUrl: "/images/private-family-resort.jpeg",
  },
  {
    slug: "cambridgeshire",
    regionName: "Cambridgeshire",
    badgeText: "Vetted Landscapers Across The UK, Ireland And Spain",
    heroHeadline: "Tell Us About Your Garden And We'll Match You With The Right Landscaper",
    heroSubheadline: "A curated network of landscapers, vetted for quality and matched to your project, your style, and your timeline. Plus an initial estimate to help you plan.",
    countyList: "For homeowners in Cambridgeshire.",
    locationPlaceholder: "e.g. CB1 1AA",
    heroImageUrl: "/images/private-family-resort.jpeg",
  },
  {
    slug: "belfast",
    regionName: "Belfast",
    badgeText: "Vetted Landscapers Across The UK, Ireland And Spain",
    heroHeadline: "Tell Us About Your Garden And We'll Match You With The Right Landscaper",
    heroSubheadline: "A curated network of landscapers, vetted for quality and matched to your project, your style, and your timeline. Plus an initial estimate to help you plan.",
    countyList: "For homeowners in Belfast and County Antrim.",
    locationPlaceholder: "e.g. BT1 1AA",
    heroImageUrl: "/images/private-family-resort.jpeg",
  },
  {
    slug: "liverpool",
    regionName: "Liverpool",
    badgeText: "Vetted Landscapers Across The UK, Ireland And Spain",
    heroHeadline: "Tell Us About Your Garden And We'll Match You With The Right Landscaper",
    heroSubheadline: "A curated network of landscapers, vetted for quality and matched to your project, your style, and your timeline. Plus an initial estimate to help you plan.",
    countyList: "For homeowners in Liverpool and Merseyside.",
    locationPlaceholder: "e.g. L1 1AA",
    heroImageUrl: "/images/private-family-resort.jpeg",
  },
  {
    slug: "essex",
    regionName: "Essex",
    badgeText: "Vetted Landscapers Across The UK, Ireland And Spain",
    heroHeadline: "Tell Us About Your Garden And We'll Match You With The Right Landscaper",
    heroSubheadline: "A curated network of landscapers, vetted for quality and matched to your project, your style, and your timeline. Plus an initial estimate to help you plan.",
    countyList: "For homeowners in Essex.",
    locationPlaceholder: "e.g. CM1 1AA",
    heroImageUrl: "/images/private-family-resort.jpeg",
  },
  {
    slug: "london",
    regionName: "London",
    badgeText: "Vetted Landscapers Across The UK, Ireland And Spain",
    heroHeadline: "Tell Us About Your Garden And We'll Match You With The Right Landscaper",
    heroSubheadline: "A curated network of landscapers, vetted for quality and matched to your project, your style, and your timeline. Plus an initial estimate to help you plan.",
    countyList: "For homeowners in Greater London.",
    locationPlaceholder: "e.g. SW1A 1AA",
    heroImageUrl: "/images/private-family-resort.jpeg",
  },
];
