#!/usr/bin/env node
/**
 * Regenerates src/config/regions.generated.ts from the Airtable Regions
 * table (only records with "Active" checked), so the fallback data used
 * when Airtable is unreachable never drifts far from what's actually live.
 *
 * Runs automatically before every `next build` via the "prebuild" script in
 * package.json - including on Vercel, where AIRTABLE_API_KEY is already
 * configured for runtime use. No cron job or manual step required: every
 * deploy re-syncs the fallback list as a side effect of building.
 *
 * Deliberately fails soft. If AIRTABLE_API_KEY is missing, the Airtable
 * request fails, or it returns zero active regions, this script leaves the
 * existing committed regions.generated.ts untouched and exits cleanly -
 * a flaky Airtable call should never be able to break a deploy or wipe out
 * good fallback data.
 */

const fs = require("fs");
const path = require("path");

const AIRTABLE_BASE_ID = process.env.AIRTABLE_BASE_ID || "appAGZVUJmvnyDAL1";
const AIRTABLE_API_KEY = process.env.AIRTABLE_API_KEY;
const REGIONS_TABLE = "Regions";
const DEFAULT_HERO_IMAGE = "/images/private-family-resort.jpeg";
const OUTPUT_PATH = path.join(__dirname, "..", "src", "config", "regions.generated.ts");

function str(value, fallback = "") {
  return typeof value === "string" && value.length > 0 ? value : fallback;
}

// Escapes a value for embedding in a double-quoted TS string literal.
function escape(value) {
  return value.replace(/\\/g, "\\\\").replace(/"/g, '\\"').replace(/\n/g, "\\n");
}

async function fetchActiveRegions() {
  const records = [];
  let offset;

  do {
    const url = new URL(
      `https://api.airtable.com/v0/${AIRTABLE_BASE_ID}/${encodeURIComponent(REGIONS_TABLE)}`
    );
    if (offset) url.searchParams.set("offset", offset);

    const res = await fetch(url.toString(), {
      headers: { Authorization: `Bearer ${AIRTABLE_API_KEY}` },
    });

    if (!res.ok) {
      throw new Error(`Airtable request failed: ${res.status} ${res.statusText}`);
    }

    const data = await res.json();
    records.push(...data.records);
    offset = data.offset;
  } while (offset);

  return records
    .filter((r) => r.fields["Active"] === true)
    .map((r) => ({
      slug: str(r.fields["Slug"]),
      regionName: str(r.fields["Region Name"]),
      badgeText: str(r.fields["Badge Text"]),
      heroHeadline: str(r.fields["Hero Headline"]),
      heroSubheadline: str(r.fields["Hero Sub-headline"]),
      countyList: str(r.fields["County List"]),
      locationPlaceholder: str(r.fields["Location Placeholder"]),
      heroImageUrl: str(r.fields["Hero Image Hosted URL"], DEFAULT_HERO_IMAGE),
    }))
    .filter((r) => r.slug.length > 0)
    .sort((a, b) => a.regionName.localeCompare(b.regionName));
}

function renderFile(regions) {
  const entries = regions
    .map(
      (r) => `  {
    slug: "${escape(r.slug)}",
    regionName: "${escape(r.regionName)}",
    badgeText: "${escape(r.badgeText)}",
    heroHeadline: "${escape(r.heroHeadline)}",
    heroSubheadline: "${escape(r.heroSubheadline)}",
    countyList: "${escape(r.countyList)}",
    locationPlaceholder: "${escape(r.locationPlaceholder)}",
    heroImageUrl: "${escape(r.heroImageUrl)}",
  }`
    )
    .join(",\n");

  return `// AUTO-GENERATED by scripts/sync-regions.js during \`npm run build\` (see the
// "prebuild" script in package.json). Do not edit by hand - any manual
// changes here are overwritten on the next build.
//
// This is fallback data only, used by src/lib/airtable.ts when Airtable is
// unreachable or misconfigured. Source of truth is the Airtable Regions
// table (base ${AIRTABLE_BASE_ID}), filtered to records with "Active" checked.
// Committed to git so a fresh checkout or a build without AIRTABLE_API_KEY
// set still has real fallback data instead of an empty list.
//
// Last synced: ${new Date().toISOString()} - ${regions.length} active region(s):
// ${regions.map((r) => r.regionName).join(", ")}.

import type { RegionData } from "@/lib/types";

export const fallbackRegions: RegionData[] = [
${entries}
];
`;
}

async function main() {
  if (!AIRTABLE_API_KEY) {
    console.warn(
      "[sync-regions] AIRTABLE_API_KEY not set - skipping fallback sync, keeping the existing regions.generated.ts as-is."
    );
    return;
  }

  try {
    const regions = await fetchActiveRegions();

    if (regions.length === 0) {
      console.warn(
        "[sync-regions] Airtable returned zero active regions - keeping the existing regions.generated.ts as-is rather than wiping the fallback list."
      );
      return;
    }

    fs.writeFileSync(OUTPUT_PATH, renderFile(regions));
    console.log(`[sync-regions] Synced ${regions.length} active region(s) into regions.generated.ts.`);
  } catch (err) {
    console.warn(
      `[sync-regions] Failed to sync from Airtable (${err instanceof Error ? err.message : err}) - keeping the existing regions.generated.ts as-is.`
    );
  }
}

main();
